

spring:
  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:file:./jpatest
    username:
    password:
  jpa:
    properties:
      hibernate:
        use_sql_comments: true
        format_sql: true
        show_sql: true
        id:
          new_generator_mapping: true
        dialect: org.hibernate.dialect.H2Dialect
        hbm2ddl:
          auto: create

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace